/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfComprador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfCvv = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfAño = new javax.swing.JTextField();
        tfMes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Ink Free", 0, 48)); // NOI18N
        jLabel4.setText("DATOS DE LA TARJETA DE CREDITO ");

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel5.setText("Nombre del comprador");

        tfComprador.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel6.setText("Apellidos");

        tfApellidos.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel7.setText("Direccion");

        tfDireccion.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ink Free", 0, 48)); // NOI18N
        jLabel8.setText("DATOS DEL COMPRADOR DE KEBAP");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel9.setText("Numero");

        tfNumero.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel10.setText("Caducidad");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel11.setText("Nombre");

        tfNombre.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel12.setText("CVV");

        tfCvv.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        bEnviar.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        bEnviar.setText("ENVIAR");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel1.setText("/");

        tfAño.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        tfMes.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNumero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCvv, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bEnviar)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(bEnviar)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        //Se encarga de que ningun campo del comprador este vacio
        if (tfComprador.getText().isEmpty() || tfApellidos.getText().isEmpty() || tfDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No puedes dejar campos en blanco en los datos del comprador", "Escribe", JOptionPane.ERROR_MESSAGE);
        }
        //estos ifs se encargan de que se añadan los valores correctos de la tarjeta de credito
        if (tfCvv.getText().length() != 3) {
            JOptionPane.showMessageDialog(rootPane, "El CVV solo tiene 3 numeros", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (TieneLetras(tfCvv.getText())) {
                JOptionPane.showMessageDialog(rootPane, "El CVV solo tiene numeros(exactamente 3)", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (tfNumero.getText().length() != 16) {
            JOptionPane.showMessageDialog(rootPane, "El numero de la tarjeta de credito solo tiene 16 numeros", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (TieneLetras(tfNumero.getText())) {
                JOptionPane.showMessageDialog(rootPane, "El numero de la tarjeta de creditos no tiene letras(exactamente 16)", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (tfMes.getText().length() != 1 && tfMes.getText().length() != 2) {
            JOptionPane.showMessageDialog(rootPane, "El campo del mes tiene que tener 1 numero o 2", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (TieneLetras(tfMes.getText())) {
                JOptionPane.showMessageDialog(rootPane, "El mes no puede tener letras", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (Integer.parseInt(tfMes.getText()) < 1 || Integer.parseInt(tfMes.getText()) > 12) {
                    JOptionPane.showMessageDialog(rootPane, "Introduce un mes valido", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        if (tfAño.getText().length() != 2) {
            JOptionPane.showMessageDialog(rootPane, "El campo del año tiene que 2 numeros", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (TieneLetras(tfAño.getText())) {
                JOptionPane.showMessageDialog(rootPane, "El año no puede tener letras", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (tfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo del nombre no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_bEnviarActionPerformed
/** Codigo que verifica si un campo tiene letras
 * @author Carlos
 * @version 1
 * @param texto
 * @return Devuelve un booleano de tipo:<br><code>True</code> si el campo tiene letras<br>
 * <code>False</code> si el campo no tiene letras
 */ 
    private boolean TieneLetras(String texto) {

        for (int i = 0; i < texto.length(); i++) {
            if (!Character.isDigit(texto.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfAño;
    private javax.swing.JTextField tfComprador;
    private javax.swing.JTextField tfCvv;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfMes;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNumero;
    // End of variables declaration//GEN-END:variables
}
