/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Loteria extends javax.swing.JFrame {

    /**
     * Creates new form Loteria
     */
    public Loteria() {
        initComponents();
        setLocationRelativeTo(this);
    }
    //declaracion de los boletos ganadores
    int euromillon = (int) (Math.random() * 99999 + 1);
    int ramadan = (int) (Math.random() * 99999 + 1);
    int navidad = (int) (Math.random() * 99999 + 1);
    int kebapLote = (int) (Math.random() * 99999 + 1);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoterias = new javax.swing.JComboBox<>();
        bComprobar = new javax.swing.JButton();
        tfBoleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loteria Kebap Manolo");
        setResizable(false);

        jLoterias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLoterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loteria del Euromillon", "Loteria Ramadan", "Loteria de Navidad", "Loteria de Kebap Manolo" }));

        bComprobar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bComprobar.setText("Comprobar");
        bComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobarActionPerformed(evt);
            }
        });

        tfBoleto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfBoleto.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Introduce el numero del boleto");

        jLabel2.setFont(new java.awt.Font("Ink Free", 0, 48)); // NOI18N
        jLabel2.setText("LOTERIA KEBAP MANOLO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tipo de boleto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBoleto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLoterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(bComprobar)
                        .addGap(191, 191, 191)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(bComprobar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobarActionPerformed
       //Se comprueba si el boleto tiene 5 numeros
        if (tfBoleto.getText().length() != 5) {
            JOptionPane.showMessageDialog(rootPane, "El boleto tiene que tener 5 caracteres", "Te has equivocado", JOptionPane.ERROR_MESSAGE);
        } else {
            //se comparan el boleto introducido por el usuario con el boleto ganador
            if (jLoterias.getSelectedItem() == "Loteria del Euromillon" && euromillon == Integer.parseInt(tfBoleto.getText())) {
                JOptionPane.showMessageDialog(rootPane, String.format("Felicidades tu boleto de Euromillon de numero %05d ha sido premiado con 1 000 000 €", euromillon), "¡Felicidades!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (jLoterias.getSelectedItem() == "Loteria del Euromillon" && euromillon != Integer.parseInt(tfBoleto.getText())) {
                    JOptionPane.showMessageDialog(rootPane, String.format("Vaya, tu boleto de Euromillon de numero %05d no ha sido premiado\nEl ganador ha sido el boleto de numero %05d", Integer.valueOf(tfBoleto.getText()), euromillon), "Vaya", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (jLoterias.getSelectedItem() == "Loteria Ramadan" && ramadan == Integer.parseInt(tfBoleto.getText())) {
                        JOptionPane.showMessageDialog(rootPane, String.format("Felicidades tu boleto Ramadan de numero %05d ha sido premiado con 500 000 €", ramadan), "¡Felicidades!", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        if (jLoterias.getSelectedItem() == "Loteria Ramadan" && ramadan != Integer.parseInt(tfBoleto.getText())) {
                            JOptionPane.showMessageDialog(rootPane, String.format("Vaya, tu boleto Ramadan de numero %05d no ha sido premiado\nEl ganador ha sido el boleto de numero %05d", Integer.valueOf(tfBoleto.getText()), ramadan), "Vaya", JOptionPane.INFORMATION_MESSAGE);
                        }
                        if (jLoterias.getSelectedItem() == "Loteria de Navidad" && navidad == Integer.parseInt(tfBoleto.getText())) {
                            JOptionPane.showMessageDialog(rootPane, String.format("Felicidades tu boleto de Navidad de numero %05d ha sido premiado con 350 000 €", navidad), "¡Felicidades!", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            if (jLoterias.getSelectedItem() == "Loteria de Navidad" && navidad != Integer.parseInt(tfBoleto.getText())) {
                                JOptionPane.showMessageDialog(rootPane, String.format("Vaya, tu boleto de Navidad de numero %05d no ha sido premiado\nEl ganador ha sido el boleto de numero %05d", Integer.valueOf(tfBoleto.getText()), navidad), "Vaya", JOptionPane.INFORMATION_MESSAGE);
                            }
                            if (jLoterias.getSelectedItem() == "Loteria de Kebap Manolo" && kebapLote == Integer.parseInt(tfBoleto.getText())) {
                                JOptionPane.showMessageDialog(rootPane, String.format("Felicidades tu boleto Kebap Manolo de numero %05d ha sido premiado con 2 000 000 € y un kebap gratis con patatas fritas (ketchup no incluido)", kebapLote), "¡Felicidades!", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                if (jLoterias.getSelectedItem() == "Loteria de Kebap Manolo" && kebapLote != Integer.parseInt(tfBoleto.getText())) {
                                    JOptionPane.showMessageDialog(rootPane, String.format("Vaya, tu boleto Kebap Manolo de numero %05d no ha sido premiado\nEl ganador ha sido el boleto de numero %05d", Integer.valueOf(tfBoleto.getText()), kebapLote), "Vaya", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                        }
    }//GEN-LAST:event_bComprobarActionPerformed
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loteria().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jLoterias;
    private javax.swing.JTextField tfBoleto;
    // End of variables declaration//GEN-END:variables
}
